# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-rotten-potatoes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-rotten-potatoes
  template:
    metadata:
      labels:
        app: mongodb-rotten-potatoes
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.6
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongouser
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongopwd

---

#MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodbrottenpotatoesservice
spec:
  selector:
    app: mongodb-rotten-potatoes
  ports:
  - port: 27017

---

#API Deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotten-potatoes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rotten-potatoes
  template:
    metadata:
      labels:
        app: rotten-potatoes
    spec:
      containers:
      - name: app
        image: fabricioveronez/rotten-potatoes:v1
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_DB
          value: admin
        - name: MONGODB_HOST
          value: mongodbrottenpotatoesservice
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: mongouser
        - name: MONGODB_PASSWORD
          value: mongopwd

---

#API Service
apiVersion: v1
kind: Service
metadata:
  name: rotten-potatoes-service
spec:
  selector:
    app: rotten-potatoes
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
